require "httparty"
require "json"

module Gateways
  class GovukOrganisationsRegisterGateway
    GOVERNMENT_ORGS =
      [
        "Attorney General's Office",
        "Cabinet Office",
        "Department for Business, Innovation & Skills",
        "Ministry of Housing, Communities and Local Government",
        "Department for Digital, Culture, Media and Sport",
        "Department for Education",
        "Department for Environment, Food & Rural Affairs",
        "Department for International Development",
        "Department for Transport",
        "Department for Work and Pensions",
        "Department of Energy & Climate Change",
        "Department of Health and Social Care",
        "Foreign, Commonwealth & Development Office",
        "HM Treasury",
        "Home Office",
        "Ministry of Defence",
        "Ministry of Justice",
        "Northern Ireland Office",
        "Office of the Advocate General for Scotland",
        "Office of the Leader of the House of Commons",
        "Office of the Leader of the House of Lords",
        "Office of the Secretary of State for Scotland",
        "Office of the Secretary of State for Wales",
        "HM Revenue & Customs",
        "Companies House",
        "Student Loans Company",
        "Advisory, Conciliation and Arbitration Service",
        "National Fraud Authority",
        "Treasury Solicitor’s Department",
        "UK Space Agency",
        "The Insolvency Service",
        "National Measurement Office",
        "Intellectual Property Office",
        "Fire Service College",
        "Ordnance Survey",
        "Planning Inspectorate",
        "Queen Elizabeth II Conference Centre",
        "Royal Parks",
        "Defence Science and Technology Laboratory",
        "Defence Support Group",
        "Met Office",
        "Service Children's Education",
        "Service Personnel and Veterans Agency",
        "UK Hydrographic Office",
        "Animal Health and Veterinary Laboratories Agency",
        "Centre for Environment, Fisheries and Aquaculture Science",
        "Forest Research",
        "Forest Enterprise (England)",
        "The Food and Environment Research Agency",
        "Marine Management Organisation",
        "Rural Payments Agency",
        "Veterinary Medicines Directorate",
        "FCO Services",
        "Wilton Park",
        "Medicines and Healthcare products Regulatory Agency",
        "HM Passport Office",
        "UK Border Agency",
        "HM Land Registry",
        "National Offender Management Service",
        "The National Archives",
        "Office of the Public Guardian",
        "HM Courts & Tribunals Service",
        "Driver and Vehicle Licensing Agency",
        "Driving Standards Agency",
        "Highways Agency",
        "Maritime and Coastguard Agency",
        "Vehicle and Operator Services Agency",
        "Vehicle Certification Agency",
        "UK Debt Management Office",
        "Forestry Commission",
        "Skills Funding Agency",
        "Valuation Office Agency",
        "The Charity Commission",
        "The Crown Estate",
        "Crown Prosecution Service",
        "Food Standards Agency",
        "Government Actuary's Department",
        "NS&I",
        "Ofsted",
        "Ofgem",
        "Ofqual",
        "Office of Rail Regulation",
        "Royal Mint",
        "Serious Fraud Office",
        "UK Statistics Authority",
        "UK Trade & Investment",
        "Horserace Betting Levy Board",
        "Higher Education Funding Council for England",
        "Council for Science and Technology",
        "Low Pay Commission",
        "Arts and Humanities Research Council",
        "British Hallmarking Council",
        "Construction Industry Training Board",
        "Economic and Social Research Council",
        "Engineering and Physical Sciences Research Council",
        "Engineering Construction Industry Training Board",
        "Medical Research Council",
        "Natural Environment Research Council",
        "Office for Fair Access",
        "Science and Technology Facilities Council",
        "Technology Strategy Board",
        "UK Atomic Energy Authority",
        "UK Commission for Employment and Skills",
        "Certification Officer",
        "Competition Appeal Tribunal",
        "Capital for Enterprise Limited",
        "Central Arbitration Committee",
        "Industrial Development Advisory Board",
        "Committee on Standards in Public Life",
        "Building Regulations Advisory Committee",
        "Homes and Communities Agency",
        "Architects Registration Board",
        "Arts Council England",
        "British Library",
        "British Museum",
        "English Heritage",
        "Gambling Commission",
        "Geffrye Museum",
        "Horniman Public Museum and Public Park Trust",
        "Imperial War Museum",
        "National Gallery",
        "National Heritage Memorial Fund",
        "Science Museum Group",
        "National Museums Liverpool",
        "National Portrait Gallery",
        "Natural History Museum",
        "Olympic Delivery Authority",
        "Royal Armouries Museum",
        "Sir John Soane's Museum",
        "Sports Grounds Safety Authority",
        "UK Sport",
        "VisitBritain",
        "Wallace Collection",
        "Big Lottery Fund",
        "British Film Institute",
        "Sport England",
        "Committee on Radioactive Waste Management",
        "Fuel Poverty Advisory Group",
        "Nuclear Liabilities Financing Assurance Board",
        "Civil Nuclear Police Authority",
        "Coal Authority",
        "Committee on Climate Change",
        "Nuclear Decommissioning Authority",
        "Consumer Council for Water",
        "Environment Agency",
        "Gangmasters and Labour Abuse Authority",
        "Joint Nature Conservation Committee",
        "Natural England",
        "Agriculture and Horticulture Development Board",
        "Sea Fish Industry Authority",
        "Health and Safety Executive",
        "Advisory Committee on Pesticides",
        "Advisory Committee on Releases to the Environment",
        "Independent Agricultural Appeals Panel",
        "Science Advisory Council",
        "Veterinary Products Committee",
        "Covent Garden Market Authority",
        "Broads Authority",
        "Dartmoor National Park Authority",
        "Exmoor National Park Authority",
        "Lake District National Park Authority",
        "New Forest National Park Authority",
        "North York Moors National Park Authority",
        "Commonwealth Scholarship Commission in the UK",
        "Equality 2025",
        "Industrial Injuries Advisory Council",
        "Social Security Advisory Committee",
        "The Pensions Advisory Service",
        "The Pensions Regulator",
        "Pension Protection Fund Ombudsman",
        "Pensions Ombudsman",
        "National Employment Savings Trust (NEST) Corporation",
        "The Water Services Regulation Authority",
        "UK Export Finance",
        "Education Funding Agency",
        "Standards and Testing Agency",
        "The Children and Family Court Advisory and Support Service",
        "Disabled Persons Transport Advisory Committee",
        "Air Accidents Investigation Branch",
        "Rail Accident Investigation Branch",
        "Care Quality Commission",
        "Human Fertilisation and Embryology Authority",
        "Human Tissue Authority",
        "Monitor",
        "Foreign Compensation Commission",
        "UK Financial Investments Limited",
        "Office for Budget Responsibility",
        "Office of Tax Simplification",
        "Office of the Immigration Services Commissioner",
        "Security Industry Authority",
        "Serious Organised Crime Agency",
        "Office of Manpower Economics",
        "Equality and Human Rights Commission",
        "Investigatory Powers Tribunal",
        "Advisory Council on the Misuse of Drugs",
        "Police Advisory Board for England and Wales",
        "Technical Advisory Board",
        "Migration Advisory Committee",
        "National DNA Database Ethics Group",
        "Police Arbitration Tribunal",
        "Police Discipline Appeals Tribunal",
        "HM Inspectorate of Constabulary and Fire & Rescue Services",
        "Independent Chief Inspector of Borders and Immigration",
        "National Museum of the Royal Navy",
        "Royal Museums Greenwich",
        "Civil Justice Council",
        "Law Commission",
        "Sentencing Council for England and Wales",
        "Victims' Advisory Panel",
        "Criminal Injuries Compensation Authority",
        "Information Commissioner's Office",
        "Judicial Appointments Commission",
        "Legal Services Commission",
        "Parole Board",
        "Youth Justice Board for England and Wales",
        "Office for National Statistics",
        "The Security Service",
        "Secret Intelligence Service",
        "Government Communications Headquarters",
        "National Army Museum",
        "Royal Air Force Museum",
        "Royal Marines Museum",
        "Fleet Air Arm Museum",
        "British Council",
        "Marshall Aid Commemoration Commission",
        "Westminster Foundation for Democracy",
        "Biotechnology and Biological Sciences Research Council",
        "Competition Service",
        "Criminal Cases Review Commission",
        "HM Prison Service",
        "HM Inspectorate of Prisons",
        "HM Inspectorate of Probation",
        "Victims' Commissioner",
        "Prisons and Probation Ombudsman",
        "Official Solicitor and Public Trustee",
        "The Legal Ombudsman",
        "Legal Services Board",
        "Judicial Appointments and Conduct Ombudsman",
        "Independent Commission for Aid Impact",
        "Advisory Committee on Business Appointments",
        "Boundary Commission for England",
        "House of Lords Appointments Commission",
        "Privy Council Office",
        "Audit Commission",
        "HM Crown Prosecution Service Inspectorate",
        "Pension Protection Fund",
        "Independent Living Fund",
        "Remploy Ltd",
        "Office of Fair Trading",
        "Competition Commission",
        "Regulatory Policy Committee",
        "Copyright Tribunal",
        "Consumer Futures",
        "Export Guarantees Advisory Council",
        "Land Registration Rule Committee",
        "UK Green Investment Bank",
        "Government Procurement Service",
        "Civil Service Commission",
        "Security Vetting Appeals Panel",
        "Senior Salaries Review Body",
        "Housing Ombudsman",
        "Leasehold Advisory Service",
        "London Thames Gateway Development Corporation",
        "Valuation Tribunal Service",
        "VisitEngland",
        "UK Anti-Doping",
        "Victoria and Albert Museum",
        "The Theatres Trust",
        "The Reviewing Committee on the Export of Works of Art and Objects of Cultural Interest",
        "Treasure Valuation Committee",
        "Ofcom",
        "Channel 4",
        "S4C",
        "BBC",
        "Historic Royal Palaces",
        "Heritage Lottery Fund (administered by the NHMF)",
        "Advisory Committee on Conscientious Objectors",
        "Advisory Group on Military Medicine",
        "Armed Forces' Pay Review Body",
        "Central Advisory Committee on Pensions and Compensation",
        "Defence Nuclear Safety Committee",
        "Defence Scientific Advisory Council",
        "National Employer Advisory Board",
        "Nuclear Research Advisory Council",
        "The Oil and Pipelines Agency",
        "Scientific Advisory Committee on the Medical Implications of Less-Lethal Weapons",
        "Veterans Advisory and Pensions Committees",
        "Service Complaints Commissioner",
        "Defence Academy of the United Kingdom",
        "Service Prosecuting Authority",
        "Defence, Press and Broadcasting Advisory Committee",
        "Royal Navy Submarine Museum",
        "Defence Sixth Form College",
        "Office of the Children's Commissioner",
        "School Teachers' Review Body",
        "National Forest Company",
        "Agricultural Wages Committee",
        "Agricultural Dwelling House Advisory Committees (x16)",
        "Plant Varieties and Seeds Tribunal",
        "Drinking Water Inspectorate",
        "Great Britain-China Centre",
        "BBC World Service",
        "Boundary Commission for Northern Ireland",
        "Northern Ireland Human Rights Commission",
        "Parades Commission for Northern Ireland",
        "Boundary Commission for Scotland",
        "Boundary Commission for Wales",
        "The Adjudicator’s Office",
        "Royal Mint Advisory Committee",
        "Supreme Court of the United Kingdom",
        "Administrative Justice and Tribunals Council",
        "Advisory Committees on Justices of the Peace",
        "The Advisory Council on National Records and Archives",
        "Civil Procedure Rule Committee",
        "Family Justice Council",
        "Family Procedure Rule Committee",
        "Independent Advisory Panel on Deaths in Custody",
        "Independent Monitoring Boards of Prisons, Immigration, Removal Centres and Short Term Holding Rooms",
        "Insolvency Rules Committee",
        "Prison Service Pay Review Body",
        "Tribunal Procedure Committee",
        "Independent Office for Police Conduct",
        "Office of Surveillance Commissioners",
        "Police Negotiating Board",
        "Directly Operated Railways Limited",
        "High Speed Two (HS2) Limited",
        "British Transport Police Authority",
        "Trinity House",
        "Northern Lighthouse Board",
        "Passenger Focus",
        "Traffic Commissioners for Great Britain",
        "Railway Heritage Committee",
        "BRB (Residuary) Ltd",
        "Trust ports",
        "Civil Aviation Authority",
        "Marine Accident Investigation Branch",
        "National Institute for Health and Care Excellence",
        "Review Board for Government Contracts",
        "Public Health England",
        "NHS England",
        "Health Research Authority",
        "NHS Trust Development Authority",
        "NHS Blood and Transplant",
        "NHS Resolution",
        "Advisory Panel on Public Sector Information",
        "Chevening Scholarship Programme",
        "London and Continental Railways Ltd",
        "Airports Commission",
        "Defence Equipment and Support",
        "Defence Infrastructure Organisation",
        "Joint Forces Command",
        "The Shareholder Executive",
        "West Northamptonshire Development Corporation",
        "Office for Life Sciences",
        "Local Government Ombudsman",
        "Chief Fire and Rescue Adviser",
        "National security and intelligence",
        "Government Equalities Office",
        "Efficiency and Reform Group",
        "Board of Trustees of the Royal Botanic Gardens Kew",
        "Disclosure and Barring Service",
        "Social Mobility and Child Poverty Commission",
        "Independent Reviewer of Terrorism Legislation",
        "Intelligence Services Commissioner",
        "Interception of Communications Commissioner",
        "Office for Low Emission Vehicles",
        "Office of the Parliamentary Counsel",
        "Criminal Procedure Rule Committee",
        "Commissioner for Public Appointments",
        "The McKay Commission",
        "The Parliamentary and Health Service Ombudsman",
        "Behavioural Insights Team",
        "Insolvency Practitioners Tribunal",
        "Advisory Committee on Clinical Excellence Awards",
        "Administration of Radioactive Substances Advisory Committee",
        "British Pharmacopoeia Commission",
        "Commission on Human Medicines",
        "Committee on Mutagenicity of Chemicals in Food, Consumer Products and the Environment",
        "Independent Reconfiguration Panel",
        "NHS Business Services Authority",
        "Review Body on Doctors' and Dentists' Remuneration",
        "NHS Pay Review Body",
        "Prime Minister's Office, 10 Downing Street",
        "Broadmoor Hospital investigation",
        "Animals in Science Committee",
        "Border Force",
        "Forensic Science Regulator",
        "Deputy Prime Minister's Office",
        "Health and Social Care Information Centre",
        "Health Education England",
        "Infrastructure UK",
        "National College for Teaching and Leadership",
        "Northumberland National Park Authority",
        "Peak District National Park Authority",
        "South Downs National Park Authority",
        "Yorkshire Dales National Park Authority",
        "Biometrics Commissioner",
        "Government Estates Management",
        "Competition and Markets Authority",
        "Groceries Code Adjudicator",
        "Surveillance Camera Commissioner",
        "Office of the Regulator of Community Interest Companies",
        "UK Visas and Immigration",
        "Government Office for Science",
        "Legal Aid Agency",
        "Export Control Joint Unit",
        "National Crime Agency",
        "Healthcare UK",
        "CESG",
        "Bona Vacantia",
        "Morecambe Bay Investigation",
        "Open Public Services",
        "Centre for the Protection of National Infrastructure",
        "Better Regulation Delivery Office",
        "Driver and Vehicle Standards Agency",
        "Tate",
        "Wave Hub",
        "Advisory Committee on Animal Feedingstuffs",
        "Advisory Committee on Novel Foods and Processes",
        "Advisory Committee on the Microbiological Safety of Food",
        "Committee on Toxicity of Chemicals in Food, Consumer Products and the Environment",
        "General Advisory Committee on Science",
        "Social Science Research Committee",
        "Independent Case Examiner",
        "National Crime Agency Remuneration Review Body",
        "Queen's Harbour Master",
        "Scottish Office",
        "Department for Education and Skills",
        "Department of Social Security",
        "Department of Education (Northern Ireland)",
        "Department of Trade and Industry",
        "Department for Constitutional Affairs",
        "Firearms Consultative Committee",
        "Animal Procedures Committee",
        "Welsh Office",
        "Department of the Environment (Northern Ireland)",
        "Monopolies and Mergers Commission",
        "Royal Commission on Criminal Justice",
        "Board of Inland Revenue",
        "Lord Chancellor's Department",
        "Victoria Climbié Inquiry",
        "Shipman Inquiry",
        "Department of Constitutional Affairs",
        "Kerr / Haslam Inquiry",
        "Office of the Legal Services Complaints Commissioner",
        "HM Courts Service",
        "Review Body for Nursing and Other Health Professions",
        "Department of Finance and Personnel for Northern Ireland",
        "Royal Commission on Environmental Pollution",
        "Department for Innovation, Universities and Skills",
        "Department for Children, Schools and Families",
        "Office for Criminal Justice Reform",
        "Department for Business, Enterprise and Regulatory Reform",
        "Scottish Law Commission",
        "Statistics Commission",
        "Independent Monitoring Commission",
        "Independent Review of the UK Postal Services Sector",
        "Office of HM Paymaster General",
        "Independent Review of Police Officer and Staff Remuneration and Conditions",
        "Royal Liverpool Childrens Inquiry",
        "Qualifications and Curriculum Authority",
        "Gaming Board for Great Britain",
        "Public Accounts Commission",
        "Derby North East Education Action Zone",
        "National Care Standards Commission",
        "Rivers Agency",
        "Department of Inland Revenue",
        "Kitts Green and Shard End Education Action Zone",
        "NHS Pensions Agency",
        "Northern Ireland Audit Office",
        "Equitable Life Inquiry",
        "Office of the Police Ombudsman for Northern Ireland",
        "Greenwich Education Action Zone",
        "Wolverhampton Education Action Zone",
        "Wednesbury Education Action Zone",
        "Bolton Education Action Zone",
        "Hamilton Oxford Education Action Zone",
        "Scottish Screen",
        "Dudley Education Action Zone",
        "Northern Ireland Council for the Curriculum, Examinations and Assessment",
        "Westminster Education Action Zone",
        "North East Derbyshire Coalfields Education Action Zone",
        "Telford and Wrekin Education Action Zone",
        "Withernsea and Southern Holderness Education Action Zone",
        "Northern Ireland Policing Board",
        "Easington and Seaham Education Action Zone",
        "North Islington Education Action Zone",
        "Stoke Education Action Zone",
        "Sunderland Education Action Zone",
        "Peterlee Education Action Zone",
        "Southend Education Action Zone",
        "National Biological Standards Board",
        "Police Service of Northern Ireland",
        "National Endowment for Science, Technology and the Arts",
        "Probation Board for Northern Ireland",
        "Public Health Laboratory Service Board",
        "Parliamentary Contributory Pension Fund",
        "Bedford Education Action Zone",
        "Leigh Park Education Action Zone",
        "Downham and Bellingham Education Action Zone",
        "Corby Education Action Zone",
        "Bristol Education Action Zone",
        "North West Shropshire Education Action Zone",
        "Wythenshawe Education Action Zone",
        "Ellesmere Port Education Action Zone",
        "Camborne, Pool and Redruth Education Action Zone",
        "Coventry Education Action Zone",
        "North Gillingham Education Action Zone",
        "Gloucester Education Action Zone",
        "East Manchester Education Action Zone",
        "Northern Ireland Social Security Agency",
        "Commission for Racial Equality",
        "Clacton and Harwich Education Action Zone",
        "Hackney Education Action Zone",
        "Hastings and St Leonards Education Action Zone",
        "Kent and Somerset Education Action Zone",
        "Hybu Cig Cymru - Meat Promotion Wales",
        "Commission for Health Improvement",
        "Bridgwater Education Action Zone",
        "Defence Analytical Services Agency",
        "H.M. Inspectorate of Explosives for Northern Ireland",
        "Valuation and Lands Agency",
        "Sentence Review Commissioners",
        "Water Service (Northern Ireland)",
        "Counter Fraud and Security Management Service",
        "Family Health Services Appeal Authority",
        "National Treatment Agency for Substance Misuse",
        "Ministry of Defence Police and Guarding Agency",
        "Sports Council for Northern Ireland",
        "Ordnance Survey of Northern Ireland",
        "Forensic Science Northern Ireland",
        "Youth Justice Agency of Northern Ireland",
        "Assets Recovery Agency",
        "Land Registers of Northern Ireland",
        "Northern Ireland Statistics and Research Agency",
        "Dingle Granby Toxteth Education Action Zone",
        "National Crime Squad",
        "National Criminal Intelligence Service",
        "Medical Supplies Agency",
        "Armed Forces Personnel Administration Agency",
        "Compensation Agency",
        "Wakefield Education Action Zone",
        "NHS Estates",
        "Equal Opportunities Commission",
        "Disability Rights Commission",
        "National Weights and Measures Laboratory",
        "Defence Estates",
        "Planning Service",
        "General Teaching Council for England",
        "NHS Purchasing and Supply Agency",
        "Defence Aviation Repair Agency",
        "UK Passport Service",
        "Millennium Commission",
        "Defence Intelligence and Security Centre",
        "Alcohol Education and Research Council",
        "South East Sheffield Education Action Zone",
        "National Probation Service",
        "Hearing Aid Council",
        "Northern Ireland Courts & Tribunals Service",
        "Criminal Records Bureau",
        "Police Complaints Authority",
        "Countryside Agency",
        "National Radiological Protection Board",
        "Arts Council of Wales",
        "Consumer Council for Postal Services",
        "Gas and Electricity Consumer Council (Energywatch)",
        "Sports Council for Wales",
        "Warship Support Agency",
        "Great Yarmouth Education Action Zone",
        "South East England Virtual Education Action Zone",
        "Heart of Slough Education Action Zone",
        "Plymouth Education Action Zone",
        "Arts Council of Northern Ireland",
        "General Social Care Council",
        "H.M. Customs and Excise",
        "Community Fund",
        "Office of the Chief Electoral Officer for Northern Ireland",
        "Office of the Oversight Commissioner",
        "Department of Health, Social Services and Public Safety",
        "Department for Regional Development",
        "Department for Social Development",
        "Office of the First Minister and Deputy First Minister",
        "Department of Enterprise, Trade and Investment",
        "Staff Commission for Education and Library Boards",
        "Labour Relations Agency",
        "Department of Agriculture and Rural Development",
        "Crown Agents Holding and Realisation Board",
        "Social Security Agency",
        "Home-Grown Cereals Authority",
        "Northern Ireland Local Government Officers' Superannuation Committee",
        "Fire Authority for Northern Ireland",
        "Community Development Foundation",
        "Northern Ireland Authority for Energy Regulation",
        "Scottish Arts Council",
        "Scottish Sports Council",
        "Learning and Skills Council",
        "Barrow Education Action Zone",
        "Speke Garston Education Action Zone",
        "East Cleveland Education Action Zone",
        "Armagh Observatory and Planetarium",
        "Northern Ireland Social Care Council",
        "Building Research Establishment",
        "Criminal Justice Inspection Northern Ireland",
        "Deepcut Review",
        "National Blood Authority",
        "UK Transplant",
        "South Bradford Education Action Zone",
        "North Stockton Education Action Zone",
        "Council for Catholic Maintained Schools",
        "Equality Commission for Northern Ireland",
        "Court of Judicature of Northern Ireland",
        "North East Education and Library Board",
        "Zahid Mubarek Inquiry",
        "Northern Ireland Legal Services Commission",
        "Veterinary Laboratories Agency",
        "Defence Procurement Agency",
        "Adult Learning Inspectorate",
        "Football Licensing Authority",
        "Environment and Heritage Service",
        "Defence Storage and Distribution Agency",
        "Training and Development Agency for Schools",
        "Northern Ireland Health and Social Services Estates Agency",
        "Health Protection Agency",
        "Food from Britain",
        "Strategic Rail Authority",
        "Special EU Programmes Body",
        "Business Development Service",
        "Northern Ireland Prison Service",
        "Dental Practice Board",
        "Dental Vocational Training Authority",
        "Mental Health Act Commission",
        "NHS Appointments Commission",
        "NHS Direct National Health Service Trust",
        "NHS Institute for Innovation and Improvement",
        "NHS Logistics Authority",
        "NHS Professionals",
        "Prescription Pricing Authority",
        "Fisheries Conservancy Board for Northern Ireland",
        "Driver and Vehicle Testing Agency",
        "General Consumer Council for Northern Ireland",
        "Northern Ireland Child Support Agency",
        "H.M. Inspectorate of Court Administration",
        "Forensic Science Service",
        "Defence Communication Services Agency",
        "Council for Healthcare Regulatory Excellence",
        "Army Base Repair Organisation",
        "OGCbuyingsolutions",
        "Disability and Carers Service",
        "Central Police Training and Development Authority",
        "Northern Ireland Tourist Board",
        "Central Science Laboratory",
        "Commission for Patient and Public Involvement in Health",
        "Disposal Services Agency",
        "Commission for Social Care Inspection",
        "Forest Service",
        "Public Lending Right Office",
        "Office of the Legal Services Ombudsman",
        "Northern Ireland Ombudsman",
        "Criminal Injuries Compensation Appeals Panel for Northern Ireland",
        "Government Car and Despatch Agency",
        "Roads Service",
        "Police Information Technology Organisation",
        "English Nature",
        "Postal Services Commission",
        "Housing Corporation",
        "Defence Medical Education and Training Agency",
        "Criminal Injuries Compensation Appeals Panel",
        "Northern Ireland Commissioner for Children and Young People",
        "Thurrock Thames Gateway Development Corporation",
        "Council for the Central Laboratory of the Research Councils",
        "Commission for Architecture and the Built Environment (CABE)",
        "Marine Fisheries Agency",
        "UK Government Decontamination Service",
        "Pension Service",
        "Central Office of Information",
        "Appeals Service Agency",
        "Defence Transport and Movements Agency",
        "Livestock and Meat Commission for Northern Ireland",
        "UK Film Council",
        "Milk Development Council",
        "New Opportunities Fund",
        "Department of Culture, Arts and Leisure",
        "Department for Employment and Learning",
        "Northern Ireland Practice and Education Council",
        "South Eastern Education and Library Board",
        "Western Education and Library Board",
        "State Veterinary Service",
        "National Patient Safety Agency",
        "Ashington Education Action Zone",
        "Loughs Agency",
        "Northern Health and Social Services Board",
        "Southern Health and Social Services Board",
        "Eastern Health and Social Services Board",
        "Western Health and Social Services Board",
        "Revenue and Customs Prosecutions Office",
        "National Museums and Galleries of Northern Ireland",
        "Waterways Ireland",
        "Food Safety Promotion Board",
        "Enterprise Ulster",
        "Pesticides Safety Directorate",
        "Meat Hygiene Service",
        "English Partnerships",
        "Particle Physics and Astronomy Research Council",
        "Meat and Livestock Commission",
        "Life Sentence Review Commissioners",
        "British Forces Post Office",
        "Rent Service",
        "Northern Ireland Judicial Appointments Commission",
        "People, Pay and Pensions Agency",
        "Defence Bills Agency",
        "Defence Vetting Agency",
        "Identity and Passport Service",
        "English Sports Council",
        "British Potato Council",
        "Healthcare Commission",
        "Commission for Rural Communities",
        "National School of Government",
        "Design Council",
        "Standards Board for England",
        "Investors in People UK",
        "Postgraduate Medical Education and Training Board",
        "NHS Information Centre",
        "Animal Health",
        "Renewable Fuels Agency",
        "Horticultural Development Council",
        "Personal Accounts Delivery Authority",
        "National Policing Improvement Agency",
        "Sutherland Inquiry",
        "Professional Oversight Board",
        "Wales Audit Office",
        "Commission for the Compact",
        "Phoenix Sports",
        "Buying Solutions",
        "East Midlands Development Agency (emda)",
        "Parole Commissioners for Northern Ireland",
        "Independent Safeguarding Authority",
        "Children's Workforce Development Council",
        "Local Better Regulation Office",
        "East of England Development Agency",
        "South West of England Regional Development Agency",
        "South East England Development Agency",
        "Northwest Regional Development Agency",
        "One North East",
        "Northwest Business Link",
        "Yorkshire Forward",
        "Pension, Disability and Carers Service",
        "ICL Inquiry",
        "Child Maintenance and Enforcement Commission",
        "Advantage West Midlands",
        "Capacitybuilders",
        "National College for School Leadership",
        "Working Ventures UK",
        "British Educational Communications and Technology Agency",
        "Nimrod Review",
        "Tenant Services Authority",
        "Northern Ireland Police Fund",
        "Museums, Libraries and Archives Council",
        "Northern Ireland Law Commission",
        "School Food Trust",
        "Office of the Commissioner for the Rights of Trade Union Members",
        "Office of the Commissioner for Protection Against Unlawful Industrial Action",
        "Bloody Sunday Inquiry",
        "Office of the Health Professions Adjudicator",
        "Royal Trustees' Office",
        "Infrastructure Planning Commission",
        "Asset Protection Agency",
        "CO2Sense",
        "Billy Wright Inquiry",
        "Redfern Inquiry",
        "SITPRO",
        "Rosemary Nelson Inquiry",
        "Office for Tenants and Social Landlords",
        "Qualifications and Curriculum Development Agency",
        "English Institute of Sport",
        "Mull of Kintyre Review",
        "North West Development Agency",
        "Young People's Learning Agency",
        "Firebuy",
        "Public Prosecution Service for Northern Ireland",
        "Baha Mousa Inquiry",
        "Creative Scotland",
        "Hillsborough Independent Panel",
        "Leveson Inquiry",
        "Patrick Finucane Review",
        "Mid Staffordshire NHS Foundation Trust Public Inquiry 2013",
        "Royal Mail",
        "Professional Standards Authority for Health and Social Care",
        "Azelle Rodney Inquiry",
        "Council on Tribunals",
        "Exchequer and Audit Department",
        "Nature Conservancy Council",
        "Office of the Lay Observer",
        "Office of Telecommunications",
        "Oftel",
        "Office of the Data Protection Registrar",
        "Polytechnics and Colleges Funding Council",
        "Inquiry into the supervision of the Bank of Credit and Commerce International",
        "National Museums of Scotland",
        "Ancient Monuments Board for Scotland",
        "Scottish Hospital Trust",
        "Welsh Development Agency",
        "Chemical and Biological Defence Establishment",
        "Department of National Heritage",
        "Legal Aid Board",
        "Independent Television Commission",
        "Board of Banking Supervision",
        "Her Majesty's Magistrates Courts Service Inspectorate",
        "Examination team on child care procedures and practice in North Wales",
        "Natural Resources Institute",
        "Further and Higher Education Funding Councils for Wales",
        "Broadcasting Standards Commission",
        "Department of the Environment, Transport and the Regions",
        "Northern Ireland Judicial Appointments Ombudsman",
        "United Kingdom Blood Transfusion Services",
        "Gowers Review of Intellectual Property",
        "Barker Review of Land Use Planning",
        "Leitch Review of Skills",
        "Cooksey Review",
        "Varney Review",
        "Eliasch Review",
        "Veterinary Residues Committee",
        "Administrative Justice and Tribunals Council Welsh Committee",
        "Lyons Inquiry into Local Government",
        "Office of the Identity Commissioner",
        "Crown Commercial Service",
        "Bank of England",
        "Independent Medical Expert Group",
        "Mid Staffordshire NHS Foundation Trust Public Inquiry 2010",
        "Welsh Government",
        "Scottish Government",
        "Northern Ireland Executive",
        "UK Co-ordinating Body",
        "HM Nautical Almanac Office",
        "Academy for Justice Commissioning",
        "Department for International Trade Defence & Security Organisation",
        "Office of the Schools Adjudicator",
        "Civil Service",
        "Operational Delivery Profession",
        "Policy Profession",
        "Project Delivery Profession",
        "Procurement profession",
        "Government Legal Service",
        "Government Communication Service",
        "Government Finance Profession",
        "Human Resources Profession",
        "Government Economic Service",
        "Internal Audit Profession",
        "Government Property Profession",
        "Government Science & Engineering Profession",
        "Government Statistical Service",
        "Government Operational Research Service",
        "Government Social Research Profession",
        "Government Planning Profession",
        "Government Planning Inspectors",
        "Government Tax Profession",
        "Government Veterinary Services",
        "Government Knowledge & Information Management Profession",
        "Government Occupational Psychology Profession",
        "Government Corporate Finance Profession",
        "British Cattle Movement Service",
        "Intelligence Analysis",
        "Government IT Profession",
        "Medical Profession",
        "Civil Service Reform",
        "Government Digital Service",
        "Macur Review",
        "The Jeffrey Review",
        "Office for Nuclear Regulation",
        "Rural Development Programme for England Network",
        "Government Chemist",
        "Company Names Tribunal",
        "Civil Nuclear Constabulary",
        "Centre for Defence Enterprise",
        "Reserve Forces' and Cadets' Associations",
        "Office for Disability Issues",
        "UKTI Education",
        "UKTI Life Sciences Organisation",
        "Immigration Enforcement",
        "Government Security Profession",
        "Military Aviation Authority",
        "Agri-Food and Biosciences Institute (Northern Ireland)",
        "Department of Justice (Northern Ireland)",
        "Information Services Division (Scotland)",
        "National Records of Scotland",
        "Civil Service Resourcing",
        "Public Health Wales",
        "Innovate UK",
        "Animal and Plant Health Agency",
        "District Valuer Services (DVS)",
        "Regeneration Investment Organisation",
        "Financial Services Organisation",
        "Police Remuneration Review Body",
        "Government Internal Audit Agency",
        "Financial Conduct Authority",
        "Stabilisation Unit",
        "Veterans UK",
        "Higher Education Statistics Agency",
        "National Counter Terrorism Security Office",
        "National Information Board",
        "Office of the Registrar of Consultant Lobbyists",
        "Single Source Regulations Office",
        "Independent Complaints Reviewer",
        "Welsh Language Commissioner",
        "Careers Wales",
        "Natural Resources Wales",
        "NHS Wales Informatics Service",
        "Estyn",
        "Schools Commissioners Group",
        "Government Legal Department",
        "National Measurement and Regulation Office",
        "Third Party Campaigning Review",
        "United Kingdom Reserve Forces Association",
        "Defence Electronics and Components Agency",
        "Highways England",
        "Government Commercial Function",
        "Office of Rail and Road",
        "Transport Focus",
        "Oil and Gas Authority",
        "Civil Service Fast Stream",
        "Independent Family Returns Panel",
        "Independent Anti-slavery Commissioner",
        "Accelerated Access Review",
        "Department of Culture, Arts and Leisure Northern Ireland",
        "British Business Bank",
        "Independent Commission on Freedom of Information",
        "Radioactive Waste Management",
        "Payment Systems Regulator",
        "Disabled People’s Employment Corporation",
        "Defence and Security Media Advisory Committee",
        "Ebbsfleet Development Corporation",
        "Commercial Court",
        "National Infrastructure Commission",
        "Historic England",
        "Infrastructure and Projects Authority",
        "Civil Service Fast Track Apprenticeship",
        "Service Complaints Ombudsman",
        "Financial Services Trade and Investment Board",
        "UK Holocaust Memorial Foundation",
        "Committee on Fuel Poverty",
        "Department for Communities (Northern Ireland)",
        "Department for the Economy (Northern Ireland)",
        "Department of Health (Northern Ireland)",
        "Department for Infrastructure (Northern Ireland)",
        "Department of Finance (Northern Ireland)",
        "Department of Agriculture, Environment and Rural Affairs (Northern Ireland)",
        "The Executive Office (Northern Ireland)",
        "National Data Guardian",
        "Digital, data and technology professions",
        "Porton Biopharma Limited",
        "Independent Dormant Assets Commission",
        "UK Government Investments",
        "Office of Financial Sanctions Implementation",
        "Regulatory Delivery",
        "Lammy Review",
        "Defence Safety Authority",
        "Pubs Code Adjudicator",
        "Social Mobility Commission",
        "Central Advisory Committee on Compensation",
        "Iraq Inquiry",
        "Department for International Trade",
        "Department for Exiting the European Union",
        "Department for Business, Energy & Industrial Strategy",
        "NHS Improvement",
        "Civil Service Board",
        "Cabinet Office Board",
        "NHS Digital",
        "The Electoral Commission",
        "Valuation Tribunal for England",
        "Defence and Security Accelerator",
        "Rail Safety and Standards Board",
        "Academy for Social Justice Commissioning",
        "Her Majesty's Government Communications Centre",
        "Preventing Sexual Violence Initiative",
        "National Cyber Security Centre",
        "Northern Ireland Housing Executive",
        "Her Majesty’s Prison and Probation Service",
        "Institute for Apprenticeships",
        "Judicial Office",
        "Education and Skills Funding Agency",
        "Regulator of Social Housing",
        "Office for Product Safety and Standards",
        "Commission for Countering Extremism",
        "Office for Civil Society",
        "Teaching Regulation Agency",
        "Government Property Agency",
        "Race Disparity Unit",
        "Single Financial Guidance Body",
        "Employment Agency Standards Inspectorate",
        "UK Council for Internet Safety",
      ].freeze

    LOCAL_AUTHORITIES =
      [
        "Bath and North East Somerset Council",
        "Blackburn with Darwen Borough Council",
        "Bedford Borough Council",
        "Birmingham City Council",
        "Bournemouth Borough Council",
        "Brighton and Hove City Council",
        "Barnsley Metropolitan Borough Council",
        "Bolton Metropolitan Borough Council",
        "Blackpool Borough Council",
        "Bracknell Forest Council",
        "City of Bradford Metropolitan District Council",
        "Bristol City Council",
        "Bury Metropolitan Borough Council",
        "Central Bedfordshire Council",
        "Cheshire East Council",
        "Cheshire West and Chester Council",
        "Calderdale Metropolitan Borough Council",
        "Cornwall Council",
        "Coventry City Council",
        "Darlington Borough Council",
        "Doncaster Metropolitan Borough Council",
        "Dudley Metropolitan Borough Council",
        "Durham County Council",
        "East Riding of Yorkshire Council",
        "Gateshead Metropolitan Borough Council",
        "Greater London Authority",
        "Halton Borough Council",
        "Herefordshire Council",
        "Hartlepool Borough Council",
        "Council of the Isles of Scilly",
        "Isle of Wight Council",
        "Hull City Council",
        "Kirklees Council",
        "Knowsley Metropolitan Borough Council",
        "Leicester City Council",
        "Leeds City Council",
        "Liverpool City Council",
        "City of London Corporation",
        "Luton Borough Council",
        "Manchester City Council",
        "Middlesbrough Borough Council",
        "Medway Council",
        "Milton Keynes Council",
        "Northumberland County Council",
        "North East Lincolnshire Council",
        "Newcastle City Council",
        "Nottingham City Council",
        "North Lincolnshire Council",
        "North Somerset  Council",
        "North Tyneside Council",
        "Oldham Metropolitan Borough Council",
        "Plymouth City Council",
        "Borough of Poole",
        "Portsmouth City Council",
        "Peterborough City Council",
        "Redcar and Cleveland Borough Council",
        "Rochdale Metropolitan Borough Council",
        "Reading Borough Council",
        "Rotherham Metropolitan Borough Council",
        "Rutland County Council",
        "Sandwell Metropolitan Borough Council",
        "Sefton Metropolitan Borough Council",
        "South Gloucestershire Council",
        "Sheffield City Council",
        "St Helens Council",
        "Shropshire Council",
        "Stockport Metropolitan Borough Council",
        "Salford City Council",
        "Slough Borough Council",
        "Sunderland City Council",
        "Solihull Metropolitan Borough Council",
        "Southend-on-Sea Borough Council",
        "Stoke-on-Trent City Council",
        "Southampton City Council",
        "Stockton-on-Tees Borough Council",
        "South Tyneside Council",
        "Swindon Borough Council",
        "Tameside Metropolitan Borough Council",
        "Telford & Wrekin Council",
        "Thurrock Council",
        "Torbay Council",
        "Trafford Metropolitan Borough Council",
        "West Berkshire Council",
        "Wigan Metropolitan Borough Council",
        "Wiltshire Council",
        "Wakefield Metropolitan District Council",
        "Walsall Metropolitan Borough Council",
        "City of Wolverhampton Council",
        "Royal Borough of Windsor and Maidenhead",
        "Wokingham Borough Council",
        "Wirral Borough Council",
        "Warrington Borough Council",
        "City of York Council",
        "Buckinghamshire County Council",
        "Aylesbury Vale District Council",
        "Chiltern District Council",
        "South Bucks District Council",
        "Wycombe District Council",
        "Cambridgeshire County Council",
        "Cambridge City Council",
        "East Cambridgeshire District Council",
        "Fenland District Council",
        "Huntingdonshire District Council",
        "South Cambridgeshire District Council",
        "Cumbria County Council",
        "Allerdale Borough Council",
        "Barrow-in-Furness Borough Council",
        "Carlisle City Council",
        "Copeland Borough Council",
        "Eden District Council",
        "South Lakeland District Council",
        "Derby City Council",
        "Derbyshire County Council",
        "Amber Valley Borough Council",
        "Bolsover District Council",
        "Chesterfield Borough Council",
        "Derbyshire Dales District Council",
        "Erewash Borough Council",
        "High Peak Borough Council",
        "North East Derbyshire District Council",
        "South Derbyshire District Council",
        "Devon County Council",
        "East Devon District Council",
        "Exeter City Council",
        "Mid Devon District Council",
        "North Devon District Council",
        "South Hams District Council",
        "Teignbridge District Council",
        "Torridge District Council",
        "West Devon Borough Council",
        "Dorset County Council",
        "Christchurch Borough Council",
        "East Dorset District Council",
        "North Dorset District Council",
        "Purbeck District Council",
        "West Dorset District Council",
        "Weymouth and Portland Borough Council",
        "Essex County Council",
        "Basildon Borough Council",
        "Braintree District Council",
        "Brentwood Borough Council",
        "Castle Point Borough Council",
        "Chelmsford City Council",
        "Colchester Borough Council",
        "Epping Forest District Council",
        "Harlow District Council",
        "Maldon District Council",
        "Rochford District Council",
        "Tendring District Council",
        "Uttlesford District Council",
        "East Sussex County Council",
        "Eastbourne Borough Council",
        "Hastings Borough Council",
        "Lewes District Council",
        "Rother District Council",
        "Wealden District Council",
        "London Borough of Barking and Dagenham",
        "London Borough of Brent",
        "London Borough of Bexley",
        "London Borough of Barnet",
        "London Borough of Bromley",
        "London Borough of Camden",
        "London Borough of Croydon",
        "London Borough of Ealing",
        "London Borough of Enfield",
        "Royal Borough of Greenwich",
        "London Borough of Havering",
        "London Borough of Hackney",
        "London Borough of Hillingdon",
        "London Borough of Hammersmith & Fulham",
        "London Borough of Hounslow",
        "London Borough of Harrow",
        "London Borough of Haringey",
        "London Borough of Islington",
        "Royal Borough of Kensington and Chelsea",
        "Royal Borough of Kingston upon Thames",
        "London Borough of Lambeth",
        "London Borough of Lewisham",
        "London Borough of Merton",
        "London Borough of Newham",
        "London Borough of Redbridge",
        "London Borough of Richmond upon Thames",
        "London Borough of Sutton",
        "London Borough of Southwark",
        "London Borough of Tower Hamlets",
        "London Borough of Waltham Forest",
        "London Borough of Wandsworth",
        "City of Westminster",
        "Gloucestershire County Council",
        "Cheltenham Borough Council",
        "Cotswold District Council",
        "Forest of Dean District Council",
        "Gloucester City Council",
        "Stroud District Council",
        "Tewkesbury Borough Council",
        "Hampshire County Council",
        "Basingstoke and Deane Borough Council",
        "East Hampshire District Council",
        "Eastleigh Borough Council",
        "Fareham Borough Council",
        "Gosport Borough Council",
        "Hart District Council",
        "Havant Borough Council",
        "New Forest District Council",
        "Rushmoor Borough Council",
        "Test Valley Borough Council",
        "Winchester City Council",
        "Hertfordshire County Council",
        "Broxbourne Borough Council",
        "Dacorum Borough Council",
        "East Hertfordshire District Council",
        "Hertsmere Borough Council",
        "North Hertfordshire District Council",
        "St Albans City and District Council",
        "Stevenage Borough Council",
        "Three Rivers District Council",
        "Watford Borough Council",
        "Welwyn Hatfield Borough Council",
        "Kent County Council",
        "Ashford Borough Council",
        "Canterbury City Council",
        "Dartford Borough Council",
        "Dover District Council",
        "Gravesham Borough Council",
        "Maidstone Borough Council",
        "Sevenoaks District Council",
        "Folkestone and Hythe Council",
        "Swale Borough Council",
        "Thanet District Council",
        "Tonbridge and Malling Borough Council",
        "Tunbridge Wells Borough Council",
        "Lancashire County Council",
        "Burnley Borough Council",
        "Chorley Borough Council",
        "Fylde Borough Council",
        "Hyndburn Borough Council",
        "Lancaster City Council",
        "Pendle Borough Council",
        "Preston City Council",
        "Ribble Valley Borough Council",
        "Rossendale Borough Council",
        "South Ribble Borough Council",
        "West Lancashire Borough Council",
        "Wyre Borough Council",
        "Leicestershire County Council",
        "Blaby District Council",
        "Charnwood Borough Council",
        "Harborough District Council",
        "Hinckley and Bosworth Borough Council",
        "Melton Borough Council",
        "North West Leicestershire District Council",
        "Oadby and Wigston Borough Council",
        "Lincolnshire County Council",
        "Boston Borough Council",
        "East Lindsey District Council",
        "City of Lincoln Council",
        "North Kesteven District Council",
        "South Holland District Council",
        "South Kesteven District Council",
        "West Lindsey District Council",
        "Norfolk County Council",
        "Breckland District Council",
        "Broadland District Council",
        "Great Yarmouth Borough Council",
        "Borough Council of King's Lynn and West Norfolk",
        "North Norfolk District Council",
        "Norwich City Council",
        "South Norfolk District Council",
        "West Northamptonshire Unitary Council",
        "Corby Borough Council",
        "Daventry District Council",
        "East Northamptonshire Council",
        "Kettering Borough Council",
        "Northampton Borough Council",
        "South Northamptonshire Council",
        "Wellingborough Borough Council",
        "Nottinghamshire County Council",
        "Ashfield District Council",
        "Bassetlaw District Council",
        "Broxtowe Borough Council",
        "Gedling Borough Council",
        "Mansfield District Council",
        "Newark and Sherwood District Council",
        "Rushcliffe Borough Council",
        "North Yorkshire County Council",
        "Craven District Council",
        "Hambleton District Council",
        "Harrogate Borough Council",
        "Richmondshire District Council",
        "Ryedale District Council",
        "Scarborough Borough Council",
        "Selby District Council",
        "Oxfordshire County Council",
        "Cherwell District Council",
        "Oxford City Council",
        "South Oxfordshire District Council",
        "Vale of White Horse District Council",
        "West Oxfordshire District Council",
        "Suffolk County Council",
        "Babergh District Council",
        "Forest Heath District Council",
        "Ipswich Borough Council",
        "Mid Suffolk District Council",
        "St Edmundsbury Borough Council",
        "Suffolk Coastal District Council",
        "Waveney District Council",
        "Somerset County Council",
        "Mendip District Council",
        "Sedgemoor District Council",
        "South Somerset District Council",
        "Taunton Deane Borough Council",
        "West Somerset District Council",
        "Surrey County Council",
        "Elmbridge Borough Council",
        "Epsom and Ewell Borough Council",
        "Guildford Borough Council",
        "Mole Valley District Council",
        "Reigate and Banstead Borough Council",
        "Runnymede Borough Council",
        "Spelthorne Borough Council",
        "Surrey Heath Borough Council",
        "Tandridge District Council",
        "Waverley Borough Council",
        "Woking Borough Council",
        "Staffordshire County Council",
        "Cannock Chase District Council",
        "East Staffordshire Borough Council",
        "Lichfield District Council",
        "Newcastle-under-Lyme Borough Council",
        "South Staffordshire Council",
        "Stafford Borough Council",
        "Staffordshire Moorlands District Council",
        "Tamworth Borough Council",
        "Warwickshire County Council",
        "North Warwickshire Borough Council",
        "Nuneaton and Bedworth Borough Council",
        "Rugby Borough Council",
        "Stratford-on-Avon District Council",
        "Warwick District Council",
        "Worcestershire County Council",
        "Bromsgrove District Council",
        "Malvern Hills District Council",
        "Redditch Borough Council",
        "Worcester City Council",
        "Wychavon District Council",
        "Wyre Forest District Council",
        "West Sussex County Council",
        "Adur District Council",
        "Arun District Council",
        "Chichester District Council",
        "Crawley Borough Council",
        "Horsham District Council",
        "Mid Sussex District Council",
        "Worthing Borough Council",
        "Liverpool City Region",
        "Sheffield City Region",
        "West of England Combined Authority",
        "Greater Manchester Combined Authority",
        "West Midlands Combined Authority",
        "Cambridgeshire and Peterborough Combined Authority",
        "Tees Valley Combined Authority",
        "East Suffolk Council",
        "West Suffolk Council",
        "Somerset West and Taunton Council",
        "Bournemouth, Christchurch and Poole Council",
        "Dorset Council",
        "Buckinghamshire Council",
      ].freeze

    def government_orgs
      GOVERNMENT_ORGS
    end

    def local_authorities
      LOCAL_AUTHORITIES
    end

    def custom_orgs
      CustomOrganisationName.all.map(&:name)
    end

    def all_orgs
      government_orgs + local_authorities + custom_orgs
    end
  end
end
