---
exclude:
  - '**/node_modules/**/*'
linters:
  ErbSafety:
    enabled: true
    exclude:
      # we exclude this as it uses html_safe deliberately.
      - '**/app/views/layouts/_form_errors.html.erb'
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Metrics/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
