inherit_gem:
  govuk-lint: configs/rubocop/all.yml
require: rubocop-rspec
AllCops:
  Exclude:
    - spec/features/upload_download_mous_spec.rb
    - spec/features/super_admin/view_organisation_list_spec.rb
    - spec/features/super_admin/sort_view_in_organisation_list_spec.rb
    - spec/features/super_admin/view_organisation_page_spec.rb
    - spec/features/super_admin/delete_organisation_as_super_admin_spec.rb
    - spec/features/super_admin/add_custom_organisation_spec.rb
    - spec/features/super_admin/view_organisation_tab_spec.rb
    - spec/features/super_admin/authorised_email_domain_spec.rb
    - spec/features/super_admin/sign_in_as_super_admin_spec.rb
    - spec/features/super_admin/edit_organisation_details_spec.rb
    - spec/models/logs_search_spec.rb
    - spec/models/ip_spec.rb
    - spec/models/location_spec.rb
    - spec/models/organisation_spec.rb
    - spec/models/authorised_email_domain_spec.rb
    - spec/models/user_spec.rb
    - spec/requests/ips/delete_spec.rb
    - spec/requests/email_domain/delete_spec.rb
    - spec/requests/monitoring/healthcheck_spec.rb
    - spec/support/notifications_service.rb
    - spec/support/confirmation_use_case.rb
    - spec/support/unlock_account_use_case_spy.rb
    - spec/support/reset_password_use_case.rb
    - spec/support/invite_use_case.rb
    - spec/facades/ips/publish_spec.rb
    - spec/gateways/s3_spec.rb
    - spec/gateways/zendesk_support_tickets_spec.rb
    - spec/gateways/govuk_organisations_register_gateway_spec.rb
    - spec/gateways/ips_spec.rb
    - spec/gateways/authorised_email_domains_spec.rb
    - spec/gateways/email_spec.rb
    - spec/gateways/sessions_spec.rb
    - spec/gateways/route53_spec.rb
    - spec/use_cases/radius/generate_ip_whitelist_spec.rb
    - spec/use_cases/generate_radius_secret_key_spec.rb
    - spec/use_cases/performance_platform/publish_locations_ips_spec.rb
    - spec/use_cases/publish_radius_whitelist_spec.rb
    - spec/use_cases/organisation/fetch_organisations_register_spec.rb
    - spec/use_cases/organisation/view_radius_ip_addresses_spec.rb
    - spec/use_cases/administrator/publish_signup_whitelist_spec.rb
    - spec/use_cases/administrator/create_support_ticket_spec.rb
    - spec/features/guidance_after_sign_in_spec.rb
    - spec/features/registration/sign_up_as_an_organisation_spec.rb
    - spec/features/registration/resend_confirmation_instructions_spec.rb
    - spec/features/contact_us_when_not_signed_in_spec.rb
    - spec/features/ips/permissions_spec.rb
    - spec/features/ips/view_ip_address_readiness_spec.rb
    - spec/features/ips/add_ip_to_existing_location_spec.rb
    - spec/features/ips/view_ip_addresses_spec.rb
    - spec/features/ips/remove_an_ip_spec.rb
