FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/default.conf
COPY organisation_records.json /usr/share/nginx/organisation_records.json
COPY local_auths_records.json /usr/share/nginx/local_auths_records.json

